spring.application.name=order-service
server.port=8081

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.template.observationEnabled=true

# PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/observability_db
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# expose actuator endpoint via HTTP
management.endpoints.web.exposure.include=*

# turn on actuator health check
management.endpoint.health.enabled = true

# allow to obtain basic information about camel routes (read only mode)
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
